# Generated by Django 6.0 on 2025-12-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='office_latitude',
            field=models.FloatField(default=27.7172),
        ),
        migrations.AddField(
            model_name='department',
            name='office_longitude',
            field=models.FloatField(default=85.324),
        ),
    ]
