# Generated by Django 6.0 on 2025-12-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_department_office_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('DECLINED', 'Declined')], default='PENDING', max_length=20),
        ),
    ]
