# Generated by Django 6.0 on 2025-12-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_emergencyrequest_fieldofficiallocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldofficiallocation',
            name='latitude',
            field=models.FloatField(default=27.7172),
        ),
        migrations.AlterField(
            model_name='fieldofficiallocation',
            name='longitude',
            field=models.FloatField(default=85.324),
        ),
    ]
