# Generated by Django 6.0 on 2025-12-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('TEAM_ARRIVED', 'Team Arrived'), ('RESOLVED', 'Resolved'), ('DECLINED', 'Declined')], default='PENDING', max_length=20),
        ),
    ]
