# Generated by Django 6.0 on 2025-12-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_fieldofficiallocation_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyrequest',
            name='current_route_step',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='route_path',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
