# Generated by Django 6.0 on 2025-12-19 18:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
