# Generated by Django 6.0 on 2025-12-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_emergencyrequest_current_route_step_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='ai_reasoning',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='priority_level',
            field=models.CharField(default='MEDIUM', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='priority_score',
            field=models.IntegerField(default=0),
        ),
    ]
