# Generated by Django 6.0 on 2025-12-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_emergencyrequest_fieldofficiallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='ai_reasoning',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='priority_level',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='priority_score',
            field=models.IntegerField(default=50),
        ),
    ]
